// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJb_5Cy8O6KD6Oh9jgo3fTNvCADzuwjo',
    appId: '1:933627410795:web:08a8c0c9d55ae4a4dcb42e',
    messagingSenderId: '933627410795',
    projectId: 'attendance-dd633',
    authDomain: 'attendance-dd633.firebaseapp.com',
    storageBucket: 'attendance-dd633.firebasestorage.app',
    measurementId: 'G-BV59495WVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh1Xll1cGonFwiZ-QEsNGN8r5LlJFYflQ',
    appId: '1:933627410795:android:57d37eb70bc4e4f3dcb42e',
    messagingSenderId: '933627410795',
    projectId: 'attendance-dd633',
    storageBucket: 'attendance-dd633.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZSS2HGowdtiALx1cn6pEyyHoI2NBc1l4',
    appId: '1:933627410795:ios:4eba5612563e0930dcb42e',
    messagingSenderId: '933627410795',
    projectId: 'attendance-dd633',
    storageBucket: 'attendance-dd633.firebasestorage.app',
    iosBundleId: 'com.example.attend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZSS2HGowdtiALx1cn6pEyyHoI2NBc1l4',
    appId: '1:933627410795:ios:4eba5612563e0930dcb42e',
    messagingSenderId: '933627410795',
    projectId: 'attendance-dd633',
    storageBucket: 'attendance-dd633.firebasestorage.app',
    iosBundleId: 'com.example.attend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATJb_5Cy8O6KD6Oh9jgo3fTNvCADzuwjo',
    appId: '1:933627410795:web:17abbd85741601e2dcb42e',
    messagingSenderId: '933627410795',
    projectId: 'attendance-dd633',
    authDomain: 'attendance-dd633.firebaseapp.com',
    storageBucket: 'attendance-dd633.firebasestorage.app',
    measurementId: 'G-1YP33N59LJ',
  );
}
